# version: "3.8"

# services:
#   react-app:
#     build: .
#     image: demoreact-app
#     container_name: demoreact-app
#     ports:
#       - "5173:80"
#     restart: unless-stopped

version: "3.8"

services:
  react-app:
    build: .
    image: ${DOCKERHUB_REPO}:${VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:80"
    restart: unless-stopped
