version: "3.8"

services:
  react-app:
    image: ${DOCKERHUB_REPO}:${VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:80"
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
