version: "3.8"

services:
  react-app:
    build:
      context: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
